import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ReactElement, useEffect, useState } from 'react'
import { ethers } from 'ethers'
// import { ApolloProvider } from "react-apollo";
// import ApolloClient from "apollo-boost";
// import { Query, graphql } from "react-apollo";
// import gql from "graphql-tag";
// const client = new ApolloClient({
//   uri: "https://countries.trevorblades.com/graphql"
// });



const Home: NextPage = () => {
  const [emoji, setEmoji] = useState()
  useEffect(() => {
    const el = document?.querySelector('#enableEthereumButton');
    el?.addEventListener('click', connectMetaMask);
    const cEl = document.querySelector('#userInput');
    cEl?.addEventListener('enter', search)
    cEl?.addEventListener('blur', search)

    return () => {
      el?.removeEventListener('click', connectMetaMask);
    }
  }, [])

  function search(el: any) {
    console.log("cEl.textContent", el.target.value);
  }

  const showWalletAddress = (account: string) => {
    if (!account) return;
    const acountEl: Element | null = document.querySelector("#showAccount");
    if (!acountEl) return;
    acountEl.innerHTML = account;
  }

  async function connectMetaMask() {
    const provider = new ethers.providers.Web3Provider(window.ethereum, "any");
    // Prompt user for account connections
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    const account = await signer.getAddress();
    showWalletAddress(account);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/ethers/5.6.9/ethers.umd.min.js"></script> */}
      </Head>

      <main className={styles.main}>
        <button id="enableEthereumButton">Connect</button>
        <h2>Account: <span id="showAccount"></span></h2>
        {/* <ApolloProvider client={client}> */}
        <div>
          <input id="userInput" />
          <div>
            {emoji}
          </div>
        </div>
        {/* </ApolloProvider> */}


      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home
